debug: false

messages:
  tryDropItem: '&7>> Вы не можете выбросить данный предмет!'
  tryMoveItem: '&7>> Перемещение предмета запрещено!'

lore:
  cantDrop: 'Не выпадает при смерти'
  personal: 'Персональный предмет'